version: '2'
services:
    pazauaa-app:
        image: pazauaa
        external_links:
            - pazauaa-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:--pazaSchouck01@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/pazauaa
            - JHIPSTER_SLEEP=60 # gives time for the database to boot before the application
    pazauaa-postgresql:
        container_name: pazauaa-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=pazauaa
            - POSTGRES_PASSWORD=

    pazaassetbddsrv-app:
        image: pazaassetbddsrv
        external_links:
            - pazaassetbddsrv-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:--pazaSchouck01@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/pazaassetbddsrv
            - JHIPSTER_SLEEP=320
    pazaassetbddsrv-postgresql:
        container_name: pazaassetbddsrv-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=pazaassetbddsrv
            - POSTGRES_PASSWORD=
    
    pazagateway-app:
        image: pazagateway
        external_links:
            - pazagateway-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:--pazaSchouck01@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/pazagateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=330
        ports:
            - 8484:8484
    pazagateway-postgresql:
        container_name: pazagateway-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=pazagateway
            - POSTGRES_PASSWORD=
    
    jhipster-registry:
        extends:
            file: jhipster-registry-full-logs.yml
            service: jhipster-registry

    jhipster-elasticsearch:
        extends:
            file: jhipster-console.yml
            service: jhipster-elasticsearch
    jhipster-logstash:
        extends:
          file: jhipster-console.yml
          service: jhipster-logstash
    jhipster-console:
        extends:
            file: jhipster-console.yml
            service: jhipster-console
