version: '2'
services:
    pazauaa-app:
        image: pazauaa
        external_links:
            - pazauaa-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:--pazaSchouck01@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/pazauaa
            - JHIPSTER_SLEEP=60 # gives time for the database to boot before the application
    pazauaa-postgresql:
        container_name: pazauaa-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=pazauaa
            - POSTGRES_PASSWORD=

    pazaassetbddsrv-app:
        image: pazaassetbddsrv
        external_links:
            - pazaassetbddsrv-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:--pazaSchouck01@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/pazaassetbddsrv
            - JHIPSTER_SLEEP=150
    pazaassetbddsrv-postgresql:
        container_name: pazaassetbddsrv-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=pazaassetbddsrv
            - POSTGRES_PASSWORD=
    
    pazagateway-app:
        image: pazagateway
        external_links:
            - pazagateway-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:--pazaSchouck01@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/pazagateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=200
        ports:
            - 8484:8484
    pazagateway-postgresql:
        container_name: pazagateway-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=pazagateway
            - POSTGRES_PASSWORD=

    pazachaingateway-app:
        image: pazachaingateway
        external_links:
            - pazachaingateway-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:--pazaSchouck01@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/pazachaingateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=200 # gives time for uaa and the cassandra cluster to start and execute the migration scripts
        ports:
            - 8485:8485
    pazachaingateway-postgresql:
        container_name: pazachaingateway-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=pazachaingateway
            - POSTGRES_PASSWORD=

    pazachainfabricsdksrv-app:
        image: pazachainfabricsdksrv
        external_links:
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:--pazaSchouck01@registry:8761/config
            - JHIPSTER_SLEEP=150 # gives time for the database to boot before the application
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry

