version: '2'
services:
    pazauaa-app:
        image: pazauaa
        external_links:
            - pazauaa-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:--pazaSchouck01@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/pazauaa
            - JHIPSTER_SLEEP=60 # gives time for the database to boot before the application
        ports:
            - 9999:9999
    pazauaa-postgresql:
        container_name: pazauaa-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=pazauaa
            - POSTGRES_PASSWORD=
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry

